/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.107
 * Generated at: 2025-07-14 17:03:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class agregar_005fconductor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/templates/footer.jspf", Long.valueOf(1752512595231L));
    _jspx_dependants.put("/templates/header_admin.jspf", Long.valueOf(1752512595236L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1752512595283L));
    _jspx_dependants.put("jar:file:/C:/Users/Hp/Documents/NetBeansProjects/metro-linea1/build/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153403082000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    pe.linea1.model.Usuario usuario = (pe.linea1.model.Usuario) session.getAttribute("usuario");
    if (usuario == null) {
        response.sendRedirect("login.jsp");
        return;
    }
    String nombre = usuario.getNombres();
    if (usuario.getApellidoPaterno() != null && !usuario.getApellidoPaterno().isEmpty())
        nombre += " " + usuario.getApellidoPaterno();
    if (usuario.getApellidoMaterno() != null && !usuario.getApellidoMaterno().isEmpty())
        nombre += " " + usuario.getApellidoMaterno();
    String foto = (usuario.getFotoPerfil() != null && !usuario.getFotoPerfil().isEmpty()) ? usuario.getFotoPerfil() : "default_avatar.png";
    String fechaHoy = new java.text.SimpleDateFormat("dd/MM/yyyy").format(new java.util.Date());

      out.write('\n');
      out.write('\n');

    pe.linea1.model.Usuario usuarioActual = (pe.linea1.model.Usuario) session.getAttribute("usuario");
    if (usuarioActual == null || !"ADMINISTRADOR".equalsIgnoreCase(usuarioActual.getRol())) {
        response.sendRedirect("login.jsp");
        return;
    }
    // ¡NO declares aquí las variables nombre ni foto!

      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark\" style=\"background-color: #2376d9;\">\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("        <a class=\"navbar-brand d-flex align-items-center\" href=\"home_admin.jsp\">\n");
      out.write("            <img src=\"images/LOGOL1.png\" alt=\"Metro Línea 1\" style=\"height:40px; margin-right:10px;\">\n");
      out.write("            Metro Línea 1\n");
      out.write("            <span class=\"badge bg-success ms-2\" style=\"font-size:0.8em;\">Administrador</span>\n");
      out.write("        </a>\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarAdmin\" aria-controls=\"navbarAdmin\" aria-expanded=\"false\" aria-label=\"Menú\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarAdmin\">\n");
      out.write("            <ul class=\"navbar-nav ms-auto align-items-center\">\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"home_admin.jsp\"><i class=\"bi bi-house\"></i> Inicio</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"notificaciones.jsp\"><i class=\"bi bi-bell\"></i> Notificaciones</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"editar_perfil.jsp\"><i class=\"bi bi-person-circle\"></i> Perfil</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"logout.jsp\"><i class=\"bi bi-box-arrow-right\"></i> Cerrar sesión</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item ms-3\">\n");
      out.write("                    <!-- USAR las variables ya declaradas en el JSP principal -->\n");
      out.write("                    <img src=\"images/");
      out.print( foto );
      out.write("\" alt=\"Foto perfil\" class=\"rounded-circle\" style=\"height:38px; width:38px; object-fit:cover; border:2px solid #fff;\">\n");
      out.write("                    <span class=\"text-white ms-2\" style=\"font-size:0.98em;\">");
      out.print( nombre );
      out.write("</span>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"css/gestion_conductores.css\">\n");
      out.write("\n");
      out.write("<div class=\"container mt-4\">\n");
      out.write("    <!-- Botón Regresar -->\n");
      out.write("    <div class=\"mb-3\">\n");
      out.write("        <button class=\"btn btn-outline-secondary\" onclick=\"window.location.href='gestion_conductores.jsp'\">\n");
      out.write("            <i class=\"bi bi-arrow-left\"></i> Regresar\n");
      out.write("        </button>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"card shadow-sm\">\n");
      out.write("        <div class=\"card-body\">\n");
      out.write("            <h2 class=\"mb-4 text-center\">Agregar Conductor</h2>\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            <form method=\"post\" action=\"AgregarConductorServlet\" autocomplete=\"off\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-4 mb-3\">\n");
      out.write("                        <label class=\"form-label\">DNI*:</label>\n");
      out.write("                        <input type=\"text\" name=\"dni\" maxlength=\"8\" required class=\"form-control\" pattern=\"\\\\d{8}\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-4 mb-3\">\n");
      out.write("                        <label class=\"form-label\">Nombres*:</label>\n");
      out.write("                        <input type=\"text\" name=\"nombres\" required class=\"form-control\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-4 mb-3\">\n");
      out.write("                        <label class=\"form-label\">Apellido paterno*:</label>\n");
      out.write("                        <input type=\"text\" name=\"apellidoPaterno\" required class=\"form-control\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-4 mb-3\">\n");
      out.write("                        <label class=\"form-label\">Apellido materno*:</label>\n");
      out.write("                        <input type=\"text\" name=\"apellidoMaterno\" required class=\"form-control\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-4 mb-3\">\n");
      out.write("                        <label class=\"form-label\">Correo*:</label>\n");
      out.write("                        <input type=\"email\" name=\"correo\" required class=\"form-control\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-4 mb-3\">\n");
      out.write("                        <label class=\"form-label\">Teléfono:</label>\n");
      out.write("                        <input type=\"text\" name=\"telefono\" class=\"form-control\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-4 mb-3\">\n");
      out.write("                        <label class=\"form-label\">Contacto emergencia:</label>\n");
      out.write("                        <input type=\"text\" name=\"contactoEmergencia\" class=\"form-control\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-4 mb-3\">\n");
      out.write("                        <label class=\"form-label\">Fecha nacimiento:</label>\n");
      out.write("                        <input type=\"date\" name=\"fechaNacimiento\" class=\"form-control\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-4 mb-3\">\n");
      out.write("                        <label class=\"form-label\">Modalidad*:</label>\n");
      out.write("                        <select name=\"modalidad\" required class=\"form-select\">\n");
      out.write("                            <option value=\"\">Seleccionar</option>\n");
      out.write("                            <option value=\"FIJO\">FIJO</option>\n");
      out.write("                            <option value=\"ROTATIVO\">ROTATIVO</option>\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-4 mb-3\">\n");
      out.write("                        <label class=\"form-label\">Base*:</label>\n");
      out.write("                        <input type=\"text\" name=\"base\" required class=\"form-control\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-4 mb-3\">\n");
      out.write("                        <label class=\"form-label\">Fecha ingreso*:</label>\n");
      out.write("                        <input type=\"date\" name=\"fechaIngreso\" required class=\"form-control\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-8 mb-3\">\n");
      out.write("                        <label class=\"form-label\">Observaciones:</label>\n");
      out.write("                        <input type=\"text\" name=\"observaciones\" class=\"form-control\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"d-flex justify-content-center mt-3 gap-2\">\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-success px-4\">Agregar</button>\n");
      out.write("                    <a href=\"gestion_conductores.jsp\" class=\"btn btn-secondary px-4\">Cancelar</a>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<footer class=\"footer mt-auto py-3 bg-light\">\n");
      out.write("  <div class=\"container text-center\">\n");
      out.write("    <span class=\"text-muted\">&copy; 2025 Metro Línea 1. Todos los derechos reservados.</span>\n");
      out.write("  </div>\n");
      out.write("</footer>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /agregar_conductor.jsp(31,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty error}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("                <div class=\"alert alert-danger\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</div>\n");
        out.write("            ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
